export * from './plugin/solid-editor'
export * from './components/editable'
export type * from './components/propTypes'
export * from './components/slate'
export * from './hooks/useReadOnly'
export * from './hooks/useSlate'
export * from './hooks/useSlateStatic'
export * from './plugin/with-solid'
